### PR TITLE
LPS-143350 Rename the Inviter role to Admin

### PR DESCRIPTION
**Pull request by stsquared99**
@ctang3 Sorry this got so delayed! I had to spend some time figuring out what the best way to handle this was since I wanted to avoid a breaking upgrade, and also had to wait for some other refactoring changes to merge first. Ended up splitting the permissions changes into a separate bug fix, so this is now a simple name change.
I think the key thing was, the upgrade in this case should be in the CT web module. The change is to the roles table, but the upgrade is for the new behavior for this web module, hence placing it here. Hope that makes sense.
If you get a chance, could you give it a quick look to see if I updated all your changes correctly? Thanks!

@xbrianlee Could you help us test this, especially the upgrades? There's a couple of stacking upgrades for the publications roles now. The only change here should be the name. Thanks!

### CODE REVIEW

**Comment by stsquared99** [comment]
ci:test

**Comment by stsquared99** [comment]
ci:test:sf

**Comment by stsquared99** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:publications

**Comment by xbrianlee** [comment]
ci:test:relevant

**Comment by xbrianlee** [comment]
ci:test:bundle

**Comment by xbrianlee** [comment]
Continuing testing in https://github.com/liferay-publications/liferay-portal/pull/3

**Comment by xbrianlee** [comment]
ci:close

**Pull request closed without merging**
